### ISSUE TITLE
Suggestions for improvement on solutions for assignment 4

### ISSUE THREAD

**Issue by nadezhdagesheva** [lse-me314/assignment04#2]
1. The suggested solution to exercise 4.1 e) violates the *hierarchy principle* – the main effects are not included in the linear model.

2. Typo in code for 4.3 b): 
eps <- rnorm(100, 0, sqrt(0.25))
*should be*
eps <- rnorm(100, 0, sd = 0.25),  since the text of the problem asks for normal distribution with mean zero and variance 0.25. Additionally, the results from the linear regression model afterwards change accordingly.

**Comment by kbenoit** [comment]
Thanks for the feedback. The output in 4.1e does not violate the hierarchy principle because all constituent terms from the interactions are automatically included Ising the (e.g.) `cylinders:displacement` notation. So below, we have the constituent terms as `cylinders`, `displacement `, and `weight`. 
```
## Coefficients:
##                          Estimate Std. Error t value Pr(>|t|)    
## (Intercept)             5.262e+01  2.237e+00  23.519  < 2e-16 ***
## cylinders               7.606e-01  7.669e-01   0.992    0.322    
## displacement           -7.351e-02  1.669e-02  -4.403 1.38e-05 ***
## weight                 -9.888e-03  1.329e-03  -7.438 6.69e-13 ***
## cylinders:displacement -2.986e-03  3.426e-03  -0.872    0.384    
## displacement:weight     2.128e-05  5.002e-06   4.254 2.64e-05 ***
```

The 4.3b code is correct because to get a _variance_ of 0.25 we need to specify a `sd = sort(0.25)` since the standard deviation is the square root of the variance.
